#!/usr/bin/env bash
# Quick Start: Web Speech API Wake Word Testing

echo "=========================================="
echo "Web Speech API - Wake Word Testing"
echo "=========================================="
echo ""
echo "Step 1: Ensure Backend is Running"
echo "  cd backend"
echo "  uvicorn main:app --reload"
echo ""
echo "Step 2: Ensure Frontend is Running (New Terminal)"
echo "  cd frontend"
echo "  npm run dev"
echo ""
echo "Step 3: Open Browser"
echo "  http://localhost:3000"
echo ""
echo "Step 4: Activate Microphone"
echo "  Click button: [ 🔇 MIC: MUTADO ]"
echo "  Should change to: [ 🎤 ESCUTANDO: QUINTA-FEIRA ]"
echo ""
echo "Step 5: Speak Commands"
echo "==========================================="
echo ""
echo "TEST CASES:"
echo ""
echo "Test 1: Basic Wake Word"
echo "  Say: 'quinta-feira'"
echo "  Expected: [WAKE-WORD] detected (but no command)"
echo ""
echo "Test 2: Wake Word + Command"
echo "  Say: 'quinta-feira listar arquivos'"
echo "  Expected:"
echo "    [SOFTWARE] Transcrição: quinta-feira listar arquivos"
echo "    [WAKE-WORD] detectada"
echo "    [USUÁRIO] listar arquivos"
echo "    [QUINTA-FEIRA] <response from backend>"
echo ""
echo "Test 3: Alternative Format"
echo "  Say: 'quinta feira abrir o navegador'"
echo "  Expected: Same as Test 2, extracted command: 'abrir o navegador'"
echo ""
echo "Test 4: Hyphenated Format"
echo "  Say: 'quinta-feira qual é a hora'"
echo "  Expected: Extracted command: 'qual é a hora'"
echo ""
echo "Test 5: Wake Word with Accent"
echo "  Say: 'quinta feira'"
echo "  Expected: Recognition works (pt-BR language setting)"
echo ""
echo "Test 6: No Wake Word (Should be Ignored)"
echo "  Say: 'abrir o bloco de notas'"
echo "  Expected: [SPEECH] Transcrição logged but no command sent"
echo ""
echo "==========================================="
echo ""
echo "INTERACTIVE TEST:"
echo "1. Click the microphone button to start listening"
echo "2. Terminal will show: [SPEECH] Escuta ativada..."
echo "3. Speak a command after 'quinta-feira'"
echo "4. Check the terminal for results"
echo "5. Click microphone again to stop listening"
echo ""
echo "EXPECTED TERMINAL LOGS:"
echo "  - [SPEECH] Escuta ativada..."
echo "  - [SPEECH] Transcrição: <your speech>"
echo "  - [WAKE-WORD] 'quinta-feira' detectada"
echo "  - [USUÁRIO] <extracted command>"
echo "  - [QUINTA-FEIRA] <backend response>"
echo ""
echo "TROUBLESHOOTING:"
echo "  • Check browser console (F12) for errors"
echo "  • Verify microphone is allowed in browser permissions"
echo "  • Test in Chrome/Edge for best compatibility"
echo "  • Speak clearly in Portuguese (pt-BR)"
echo ""
echo "=========================================="
